[package]
name = "mlir-option-dialect"
version = "0.1.0"
edition = "2024"
authors = ["Jared Hoberock <jaredhoberock@gmail.com>"]

[dependencies]
melior = "0.24"
mlir-sys = "0.5.0"

[lib]
name = "option_dialect"
path = "src/lib.rs"
